#!/bin/bash

CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=/usr/local -DBUILD_SHARED=ON -DBUILD_STATIC=ON -DBUILD_DRAFTS=OFF -DBUILD_TESTING=OFF"

cmake -H"$SHOWTIME_SOURCE" -B"$SHOWTIME_BUILD" -G "Unix Makefiles" $CMAKE_FLAGS
cmake --build $SHOWTIME_BUILD --config Release
