language: C++

branches:
  only:
  - master
  - develop
  - travis

cache:
  directories:
  - apt
  - $TRAVIS_BUILD_DIR/linuxbrew
  - $TRAVIS_BUILD_DIR/boost

sudo: required 

compiler:
  - clang
  - gcc

env:
  global:
  - BUILD_FOLDER=$TRAVIS_BUILD_DIR
  - GENERATOR="Unix Makefiles"
  - USE_LOCAL_BOOST=1
  - BOOST_ROOT=$TRAVIS_BUILD_DIR/boost
  - LINUXBREWHOME=$BUILD_FOLDER/linuxbrew

  matrix:
  - CONFIG=Debug
  - CONFIG=Release

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
  		sudo apt-get -qq update;
      	sudo apt-get install build-essential curl file git python-setuptools;
	  	sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      	export USE_LOCAL_BOOST=1;
    fi
  - test -d $HOME/.linuxbrew/bin || git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew

install:
  - test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
  - test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
  - test -r ~/.bash_profile && echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bash_profile
  - echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.profile
  - if [ $LINUXBREW_EXISTS -eq 0 ]; then travis_wait 40 brew install boost; fi
  - if [ $LINUXBREW_EXISTS -eq 0 ]; then travis_wait 40 brew install czmq; fi
  - if [ $LINUXBREW_EXISTS -eq 0 ]; then brew install msgpack; fi
  - if [ $LINUXBREW_EXISTS -eq 0 ]; then brew install fmt; fi

script:
  - mkdir build
  - GENERATOR_ARGS="";
  - if [ $USE_LOCAL_BOOST ]; then GENERATOR_ARGS="USE_LOCAL_BOOST=ON BOOST_ROOT=$BOOST_ROOT"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then GENERATOR_ARGS="$GENERATOR_ARGS -DCMAKE_PREFIX_PATH=$LINUXBREWHOME;${CMAKE_PREFIX_PATH}"; fi
  - cmake -H. -B./build -G "$GENERATOR" $GENERATOR_ARGS
  - cmake --build ./build --config $CONFIG

  # Run tests
  - pushd "$BUILD_FOLDER/build"
  - ctest -C Debug -V --output-on-fail
