language: C++

branches:
  only:
  - master
  - develop
  - travis

cache:
  directories:
  - apt
  - $HOME/.linuxbrew

sudo: required 

compiler:
  - clang
  - gcc

env:
  global:
  - BUILD_FOLDER=$TRAVIS_BUILD_DIR
  - HOMEBREW_FORCE_VENDOR_RUBY=1
  - PATH="$TRAVIS_BUILD_DIR/.linuxbrew/bin:$PATH"
  - GENERATOR="Unix Makefiles"
  - USE_LOCAL_BOOST=1
  matrix:
  - CONFIG=Debug
  - CONFIG=Release

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get install build-essential curl file git python-setuptools;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      if [ -z "$(ls -A $TRAVIS_BUILD_DIR/.linuxbrew)" ]; then
        echo "Installing linuxbrew to $TRAVIS_BUILD_DIR/.linuxbrew";
        git clone https://github.com/Linuxbrew/brew.git $TRAVIS_BUILD_DIR/.linuxbrew;
      else
        echo "Found existing linuxbrew directory";
      fi
    fi
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - if [ ! $USE_LOCAL_BOOST ]; then travis_wait brew install boost; fi
  - travis_wait brew install czmq
  - travis_wait brew install msgpack
  - travis_wait brew install fmt

script:
  - mkdir build
  - GENERATOR_ARGS="";
  - if [ $USE_LOCAL_BOOST ]; then GENERATOR_ARGS=USE_LOCAL_BOOST=ON; fi
  - cmake -H. -B./build -G "$GENERATOR" -D$GENERATOR_ARGS
  - cmake --build ./build --config $CONFIG

  # Run tests
  - pushd "%BUILD_FOLDER%/build"
  - ctest -C Debug -V --output-on-fail
