language: C++

branches:
  only:
  - master
  - develop
  - travis

cache:
  directories:
  - apt
  - /home/linuxbrew/.linuxbrew

sudo: required 

env:
  global:
  - BUILD_FOLDER=$TRAVIS_BUILD_DIR
  - GENERATOR="Unix Makefiles"
  - USE_LOCAL_BOOST=1
  - LINUXBREWHOME=/home/linuxbrew/.linuxbrew
  - CMAKE_PATH=$TRAVIS_BUILD_DIR/cmake

  matrix:
  - CONFIG=Debug
  - CONFIG=Release

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.9
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.9 CC=clang-3.9
      addons:
        apt:
          packages:
            - clang-3.9
          sources: *sources
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get install build-essential curl file git python-setuptools;
      wget https://cmake.org/files/v3.11/cmake-3.11.0-rc2-Linux-x86_64.sh --quiet;
      sudo bash cmake-3.11.0-rc2-Linux-x86_64.sh --skip-license --prefix=$CMAKE_PATH;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      	export USE_LOCAL_BOOST=1;
    fi

install:
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_wait 30 $BUILD_FOLDER/.travis/install_boost.sh; fi
  # Output something every 10 minutes or Travis kills the job
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash $BUILD_FOLDER/.travis/install_linuxbrew_dependencies.sh; fi
  # Killing background sleep loop
  - kill %1

script:
  - CMAKE_BIN=$CMAKE_PATH/bin/cmake
  - CTEST_BIN=$CMAKE_PATH/bin/ctest
  - echo $($CMAKE_BIN --version);
  - mkdir build
  - GENERATOR_ARGS="-DUSE_HUNTER=OFF";
  - if [ $USE_LOCAL_BOOST ]; then GENERATOR_ARGS="$GENERATOR_ARGS -DUSE_LOCAL_BOOST=ON"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then GENERATOR_ARGS="$GENERATOR_ARGS -DCMAKE_PREFIX_PATH=$LINUXBREWHOME;${CMAKE_PREFIX_PATH}"; fi
  - $CMAKE_BIN -H$TRAVIS_BUILD_DIR -B$TRAVIS_BUILD_DIR/build -G "$GENERATOR" $GENERATOR_ARGS -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
  - $CMAKE_BIN --build $TRAVIS_BUILD_DIR/build --config $CONFIG 

  # Run tests
  - pushd "$BUILD_FOLDER/build"
  - $CTEST_BIN -C Debug -V --output-on-fail
