language: C++

branches:
  only:
  - master
  - develop
  - travis

cache:
  directories:
  - apt
  - /home/linuxbrew/.linuxbrew

sudo: required 

compiler:
  - clang
  - gcc

env:
  global:
  - BUILD_FOLDER=$TRAVIS_BUILD_DIR
  - GENERATOR="Unix Makefiles"
  - USE_LOCAL_BOOST=1
  - LINUXBREWHOME=/home/linuxbrew/.linuxbrew

  matrix:
  - CONFIG=Debug
  - CONFIG=Release

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get install build-essential curl file git python-setuptools;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      	export USE_LOCAL_BOOST=1;
    fi

install:
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_wait 30 $BUILD_FOLDER/.travis/install_boost.sh; fi
  # Output something every 10 minutes or Travis kills the job
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash $BUILD_FOLDER/.travis/install_linuxbrew_dependencies.sh; fi
  # Killing background sleep loop
  - kill %1

script:
  - mkdir build
  - GENERATOR_ARGS="-DUSE_HUNTER=OFF";
  - if [ $USE_LOCAL_BOOST ]; then GENERATOR_ARGS="$GENERATOR_ARGS -DUSE_LOCAL_BOOST=ON"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then GENERATOR_ARGS="$GENERATOR_ARGS -DCMAKE_PREFIX_PATH=$LINUXBREWHOME;${CMAKE_PREFIX_PATH}"; fi
  - cmake -H$TRAVIS_BUILD_DIR -B$TRAVIS_BUILD_DIR/build -G "$GENERATOR" $GENERATOR_ARGS
  - cmake --build $TRAVIS_BUILD_DIR/build --config $CONFIG

  # Run tests
  - pushd "$BUILD_FOLDER/build"
  - ctest -C Debug -V --output-on-fail
