branches:
  only:
  - master
  - develop
  - travis

language: shell

sudo: false 

os: 
  - linux
  - osx
dist: xenial
osx_image: xcode10.1

addons:
  apt:
    packages:
      - curl
  homebrew:
    brewfile: true
    update: true

stages:
  - build
  - test

before_install:
  # Set common env variables
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PREFIX=/usr/local;
      echo $(which brew);
      echo $PATH;
    fi

  # Create linuxbrew prefix
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export PREFIX=/home/linuxbrew/.linuxbrew;
    fi

  # Set prefix search path to homebrew folder for library discovery
  - GENERATOR_ARGS="$GENERATOR_ARGS -DCMAKE_PREFIX_PATH=$PREFIX;${CMAKE_PREFIX_PATH}"

jobs:
  include:
    - stage: dependencies
      language: shell
      install:
        # Output something every 10 minutes or Travis kills the job
        - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &

        # Install linuxbrew dependencies
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            export PATH=$PREFIX/bin:$PREFIX/sbin:$PATH;
            export MANPATH=$PREFIX/share/man:$MANPATH;
            export INFOPATH=$PREFIX/share/info:$INFOPATH;
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
            hash -r;
            echo $(which brew);
            echo $PATH;
          fi

        # Install homebrew dependencies
        - brew update
        - brew bundle || true

        # Kill background sleep loop
        - kill %1
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /home/linuxbrew/.linuxbrew

    - stage: build
      language: cpp
      env:
        - BUILD_TYPE=Debug
      before_install:
        - brew list -1 | while read line; do brew unlink $line; brew link $line; done
      script: &build_lib
        # Set installation prefix
        - GENERATOR_ARGS="$GENERATOR_ARGS -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install"

        # Shared and static libraries
        - GENERATOR_ARGS="$GENERATOR_ARGS -DBUILD_SHARED=ON -DBUILD_STATIC=ON"

        # Build and install project
        - cmake -H$TRAVIS_BUILD_DIR -B$TRAVIS_BUILD_DIR/build -G "$GENERATOR" $GENERATOR_ARGS
        - cmake --build $TRAVIS_BUILD_DIR/build --BUILD_TYPE $CONFIG
        #- cmake --build $TRAVIS_BUILD_DIR/build --target install --BUILD_TYPE $BUILD_TYPE
      cache:
        directories:
        - $TRAVIS_BUILD_DIR/build
        - $TRAVIS_BUILD_DIR/install
      
    - stage: build
      language: cpp
      env:
        - BUILD_TYPE=Release
      before_install:
        - brew list -1 | while read line; do brew unlink $line; brew link $line; done
      script: *build_lib
      cache:
        directories:
        - $TRAVIS_BUILD_DIR/build
        - $TRAVIS_BUILD_DIR/install
          
    - stage: test
      language: cpp
      env: BUILD_TYPE=Debug
      script: &test_cpp
        - pushd $TRAVIS_BUILD_DIR/build
        - ctest -C $BUILD_TYPE --output-on-fail --no-compress-output -T Test --timeout 320

    - stage: test
      language: cpp
      env: BUILD_TYPE=Release
      script: *test_cpp

    - stage: test
      language: python
      env: BUILD_TYPE=Release
      script:
        - GENERATOR_ARGS="$GENERATOR_ARGS -DBINDINGS_PYTHON=ON -DBINDINGS_PYTHON_TESTS=ON"
        - cmake -H$TRAVIS_BUILD_DIR -B$TRAVIS_BUILD_DIR/build -G "$GENERATOR" $GENERATOR_ARGS
        - cmake --build $TRAVIS_BUILD_DIR/build --target install --BUILD_TYPE $BUILD_TYPE
        - pushd $TRAVIS_BUILD_DIR/build
        - ctest -C $CONFIG --output-on-fail --no-compress-output -T Test --timeout 320

    - stage: test
      language: ruby
      env: BUILD_TYPE=Release

    - stage: test
      language: csharp
      env: BUILD_TYPE=Release
      homebrew:
        casks:
        - dotnet-sdk
