version: '{build}'

branches:
  only:
  - master
  - develop
  - appveyor

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - .appveyor/
    - src/
    - include/

cache: 
#- dependencies
- dependencies -> .appveyor/cleanup-appveyor-cache.txt

clone_folder: C:/projects/showtime-cpp

image:
- Visual Studio 2017

configuration:
- Debug
- Release

platform:
- x64

environment:
  matrix:
  - GENERATOR: "Visual Studio 15 2017 Win64"
    PYTHON: "C:/Python36-x64"
    BOOST_ROOT: "C:/Libraries/boost_1_67_0"

matrix:
  fast_finish: true

install:
- cmd: |-
    @echo off
    set BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER%
    set DEPENDENCY_DIR=%APPVEYOR_BUILD_FOLDER%/dependencies
    set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%/install

    REM APPVEYOR install:
    REM ----------------------
    appveyor AddMessage "Installing dependencies"
    call %BUILD_FOLDER%/install_dependencies.bat --build-dir %BUILD_FOLDER% --config %CONFIGURATION%
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_PREFIX_PATH="%DEPENDENCY_DIR%/install;%DEPENDENCY_DIR%/swig;${CMAKE_PREFIX_PATH}"
    set CMAKE_BIN=%DEPENDENCY_DIR%/cmake/bin/cmake
    set CTEST_BIN=%DEPENDENCY_DIR%/cmake/bin/ctest

build_script:
- cmd: |-
    @echo off
    REM APPVEYOR build_script:
    REM ----------------------
    mkdir build
    appveyor AddMessage "Building Showtime project with cmake"
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBINDINGS_DOTNET=ON -DBINDINGS_DOTNET_TESTS=ON
    REM set CMAKE_FLAGS=%CMAKE_FLAGS% -DBINDINGS_UNITY=ON -DUNITY_EXECUTABLE:PATHNAME="%DEPENDENCY_DIR%/unity/Editor/Unity.exe"
    REM set CMAKE_FLAGS=%CMAKE_FLAGS% -DBINDINGS_PYTHON=ON -DBINDINGS_PYTHON_TESTS=ON -DPYTHON_EXECUTABLE=%PYTHON%/python.exe
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR%
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBoost_DEBUG=ON -DBoost_COMPILER=-vc141
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBUILD_SHARED=ON
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBUILD_STATIC=ON
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBOOST_ROOT:PATHNAME="%BOOST_ROOT%" -DBOOST_INCLUDEDIR:PATHNAME="%BOOST_ROOT%" -DBOOST_LIBRARYDIR:PATHNAME="%BOOST_ROOT%/lib64-msvc-14.1"
    
    %CMAKE_BIN% -H. -B"%BUILD_FOLDER%/build" -G "%GENERATOR%" %CMAKE_FLAGS%

    appveyor AddMessage "Building Showtime (all)"
    %CMAKE_BIN% --build "%BUILD_FOLDER%/build" --target ALL_BUILD --config %CONFIGURATION% -- /nologo /verbosity:minimal
    appveyor AddMessage "Showtime build (all) exited with status %errorlevel%"

    appveyor AddMessage "Installing Showtime"
    %CMAKE_BIN% --build "%BUILD_FOLDER%/build" --target INSTALL --config %CONFIGURATION% -- /nologo /verbosity:minimal
    appveyor AddMessage "Showtime install (all) exited with status %errorlevel%"

# after_build:
# - ps: Get-ChildItem $env:BUILD_FOLDER/build/bindings/unity/ShowtimeExampleProject/*.unitypackage | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
- cmd: |-
    @echo off
    powershell -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))"

    REM APPVEYOR test_script:
    REM ---------------------
    REM call %BUILD_FOLDER%\.appveyor\run_tests.bat
    
