version: '{build}'

branches:
  only:
  - master
  - develop
  - appveyor

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - .appveyor/
    - src/
    - include/

cache: 
#- dependencies
- dependencies -> .appveyor/cleanup-appveyor-cache.txt

clone_folder: C:/projects/showtime-cpp

image:
- Visual Studio 2019

configuration:
- Debug
- Release

platform:
- x64

environment:
    GENERATOR: "Visual Studio 16 2019"
    MSVC_VER: "msvc-14.2"
    BOOST_ROOT: "C:/Libraries/boost_1_71_0"
    BUILD_FOLDER: "%APPVEYOR_BUILD_FOLDER%/build"
    DEPENDENCY_DIR: "%APPVEYOR_BUILD_FOLDER%/build/dependencies"
    INSTALL_DIR: "%APPVEYOR_BUILD_FOLDER%/build/dependencies/install"
    PATH: "%PROGRAMFILES%/CMake/bin;%PATH%"
    matrix:
    - NATIVE: true
    - PYTHON_VER: 2
    - PYTHON_VER: 3
    - DOTNET_VER: v4.7.2
    - DOTNET_VER: netstandard2.0
    - DOTNET_VER: netstandard2.1

matrix:
    fast_finish: true

install:
- ps: |-
    mkdir $Env:BUILD_FOLDER
    mkdir $Env:DEPENDENCY_DIR
    mkdir $Env:INSTALL_DIR

    git -C $Env:APPVEYOR_BUILD_FOLDER submodule init
    git -C $Env:APPVEYOR_BUILD_FOLDER submodule update

    if($Env:PYTHON_VER -ne $null){
        choco install -y python$env:PYTHON_VER -ia "CompileAll=1 Include_debug=1 Include_symbols=1" > $null
    }
    if($Env:DOTNET_VER -ne $null){
        choco install -y dotnetcoresdk > $null
    }

    choco install -y swig > $null
    choco install -y cmake > $null
    refreshenv

    & "$Env:APPVEYOR_BUILD_FOLDER/install_dependencies.ps1" -build_dir $Env:BUILD_FOLDER -config $Env:CONFIGURATION -without_boost

before_build:
- ps: |-
    $CMAKE_FLAGS= @(
        "-S", "$env:APPVEYOR_BUILD_FOLDER",
        "-B", "$env:BUILD_FOLDER" 
        "-G", "Visual Studio 16 2019",
        "-A", "x64",
        "-DCMAKE_PREFIX_PATH=$env:INSTALL_DIR/$env:MSVC_VER",
        "-DBUILD_SHARED=ON",
        "-DBUILD_STATIC=ON",
        "-DBUILD_DRAFTS=OFF",
        "-DBUILD_TESTING=ON",
        "-DBOOST_ROOT:PATHNAME=$env:BOOST_ROOT",
        "-DBOOST_INCLUDEDIR:PATHNAME=$env:BOOST_ROOT",
        "-DBOOST_LIBRARYDIR:PATHNAME=$env:BOOST_ROOT/lib64-msvc-14.1"
    )

    if($Env:PYTHON_VER -ne $null){
        & pip$env:PYTHON_VER install wheel
        $CMAKE_FLAGS += @(
            "-DBINDINGS_PYTHON=ON",
            "-DBINDINGS_PYTHON_VERSION_MAJOR=$env:PYTHON_VER"
        )
    }
     if($Env:DOTNET_VER -ne $null){
        $CMAKE_FLAGS += @(
            "-DBINDINGS_DOTNET=ON",
            "-DBINDINGS_DOTNET_CSPROJ=ON",
            "-DBINDINGS_DOTNET_FRAMEWORK_VERSION=$Env:DOTNET_VER",
            "-DADD_GENERATED_MSVC_PROJECTS=OFF"
        )
    }

    cmake @CMAKE_FLAGS
    cmake --build "$env:BUILD_FOLDER" --config $Env:CONFIGURATION

build:
  parallel: true
  project: $(BUILD_FOLDER)/Showtime.sln
  verbosity: minimal

test_script:
- ps: |
    Push-Location -Path "$env:BUILD_FOLDER"
    & ctest -C $env:CONFIGURATION --output-on-fail --no-compress-output -T Test -j 4 --timeout 320
    $result = Get-Childitem -ErrorAction SilentlyContinue -Recurse –Path $env:BUILD_FOLDER/Testing/*.xml
    $XSLInputElement = New-Object System.Xml.Xsl.XslCompiledTransform
    $XSLInputElement.Load("https://raw.githubusercontent.com/rpavlik/jenkins-ctest-plugin/master/ctest-to-junit.xsl")
    $XSLInputElement.Transform($result[0].FullName, (Join-Path (Resolve-Path .) "ctest-to-junit-results.xml"))
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ctest-to-junit-results.xml))
    Pop-Location
