version: '{build}'

branches:
  only:
  - master
  - develop
  - appveyor

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - .appveyor/
    - src/
    - include/

cache: 
#- dependencies
- dependencies -> .appveyor/cleanup-appveyor-cache.txt

clone_folder: C:/projects/showtime-cpp

image:
- Visual Studio 2019

configuration:
- Debug
- Release

platform:
- x64

environment:
    GENERATOR: "Visual Studio 16 2019 Win64"
    BOOST_ROOT: "C:/Libraries/boost_1_69_0"
    BUILD_FOLDER: "%APPVEYOR_BUILD_FOLDER%/build"
    DEPENDENCY_DIR: "%APPVEYOR_BUILD_FOLDER%/dependencies"
    INSTALL_DIR: "%APPVEYOR_BUILD_FOLDER%/install"
    PATH: "%PROGRAMFILES%/CMake/bin;%PATH%"
    matrix:
    - PYTHON_VER: 2
    - PYTHON_VER: 3

matrix:
    fast_finish: true

install:
- ps: |-
    mkdir build
    choco install -y python$env:PYTHON_VER -ia "CompileAll=1 Include_debug=1 Include_symbols=1" > $null
    choco install -y swig > $null
    choco install -y cmake > $null
    refreshenv
    cmd.exe /c "call $env:APPVEYOR_BUILD_FOLDER/install_dependencies.bat --build-dir $env:BUILD_FOLDER --config $env:CONFIGURATION"

before_build:
- ps: |-
    $CMAKE_FLAGS = -DCMAKE_PREFIX_PATH="$env:INSTALL_DIR
    $CMAKE_FLAGS += -DBINDINGS_DOTNET=ON -DBINDINGS_DOTNET_FRAMEWORK_VERSION=v4.7.2
    $CMAKE_FLAGS += -DBINDINGS_PYTHON=ON -DBINDINGS_PYTHON_VERSION_MAJOR=$env:PYTHON_VER
    $CMAKE_FLAGS += -DBUILD_SHARED=ON -DBUILD_STATIC=ON -DBUILD_DRAFTS=ON
    $CMAKE_FLAGS += -DBOOST_ROOT:PATHNAME="$env:BOOST_ROOT" -DBOOST_INCLUDEDIR:PATHNAME="$env:BOOST_ROOT" -DBOOST_LIBRARYDIR:PATHNAME="$env:BOOST_ROOT/lib64-msvc-14.1"
    cmake -H"$env:APPVEYOR_BUILD_FOLDER" -B"$env:BUILD_FOLDER" -G "$env:GENERATOR" $CMAKE_FLAGS

build:
  parallel: true
  project: $(BUILD_FOLDER)/Showtime.sln
  verbosity: minimal

test_script:
- ps: |
    Push-Location -Path "$env:BUILD_FOLDER"
    & $env:CTEST_BIN -C $env:CONFIGURATION --output-on-fail --no-compress-output -T Test -j 2 --timeout 320
    $result = Get-Childitem -ErrorAction SilentlyContinue -Recurse –Path $env:BUILD_FOLDER/Testing/*.xml
    $XSLInputElement = New-Object System.Xml.Xsl.XslCompiledTransform
    $XSLInputElement.Load("https://raw.githubusercontent.com/rpavlik/jenkins-ctest-plugin/master/ctest-to-junit.xsl")
    $XSLInputElement.Transform($result[0].FullName, (Join-Path (Resolve-Path .) "ctest-to-junit-results.xml"))
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ctest-to-junit-results.xml))
    Pop-Location
