version: '{build}'

branches:
  only:
  - develop
cache: C:/projects/dependencies

clone_folder: c:/projects/showtime-cpp

image:
- Visual Studio 2017

configuration:
- Debug
- Release

platform:
- x64

environment:
  matrix:
  - GENERATOR: "Visual Studio 12 2013 Win64"
  - GENERATOR: "Visual Studio 14 2015 Win64"
  - GENERATOR: "Visual Studio 15 2017 Win64"

matrix:
  fast_finish: true

before_build:
- cmd: |-
    REM Set up dependency directory
    cd %APPVEYOR_BUILD_FOLDER%
    set DEPENDENCY_DIR="%APPVEYOR_BUILD_FOLDER%/dependencies"
    mkdir %DEPENDENCY_DIR%
    cd %DEPENDENCY_DIR%

    REM Aquire patched hunterized CZMQ 
    git clone https://github.com/mystfit/czmq.git
    cd czmq
    git checkout hunter-v4.1.0
    mkdir build
    mkdir install
    cmake -H. -B./build -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX="./install"
    cmake --build ./build --config %CONFIGURATION% --target INSTALL

    REM Aquire patched hunterized msgpack
    cd %DEPENDENCY_DIR%
    git clone https://github.com/mystfit/msgpack-c.git
    cd msgpack-c
    git checkout hunter-2.1.5
    mkdir build
    mkdir install
    cmake -H. -B./build -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX="./install"
    cmake --build ./build --config %CONFIGURATION% --target INSTALL

build_script:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%
    mkdir build
    cd build
    cmake .. -G "%GENERATOR%" -Dczmq_DIR="%DEPENDENCY_DIR%/czmq/build/install/share/cmake/czmq" -DMsgPack_DIR="%DEPENDENCY_DIR%/msgpack-c/build/install/lib/cmake/msgpack" -DHUNTER_STATUS_DEBUG=ON
    cmake --build . --config %CONFIGURATION%

before_test:
- cmd: |-
    REM Copy CZMQ dlls into build folder (manually until CMake can do this automagically)
    if %CONFIGURATION% == Debug set LIBCZMQ_DLL=libczmqd.dll
    if %CONFIGURATION% == Release set LIBCZMQ_DLL=libczmq.dll
    cmake -E copy "%DEPENDENCY_DIR%/czmq/install/bin/%LIBCZMQ_DLL%" "%APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/"

test_script:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%/build
    ctest -C Debug -V --output-on-fail

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - include/
