version: '{build}'

branches:
  only:
  - master
  - develop
  - appveyor

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - include/

cache: 
- dependencies -> .appveyor\cleanup-appveyor-cache.txt

clone_folder: c:/projects/showtime-cpp

image:
- Visual Studio 2017

configuration:
- Debug
- Release

platform:
- x64

environment:
  matrix:
  - GENERATOR: "Visual Studio 15 2017 Win64"

matrix:
  fast_finish: true

install:
- cmd: |-
    @echo off
    set BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER%
    set DEPENDENCY_DIR=%APPVEYOR_BUILD_FOLDER%\dependencies
    set HUNTER_ROOT=%DEPENDENCY_DIR%\hunter_root
    set BOOST_ROOT=C:\Libraries\boost_1_65_1

    REM APPVEYOR install:
    REM ----------------------
    appveyor AddMessage "Manually installing patched hunter dependencies (czmq, msgpack)"
    call "%BUILD_FOLDER%\.appveyor\install_dependencies.bat"
    set CMAKE_FLAGS=-DCMAKE_PREFIX_PATH="%DEPENDENCY_DIR%\install;${CMAKE_PREFIX_PATH}"
    REM set CMAKE_FLAGS=%CMAKE_FLAGS% -DUSE_LOCAL_BOOST=ON
    REM set CMAKE_FLAGS=%CMAKE_FLAGS% -DBOOST_ROOT="%BOOST_ROOT%"
    REM set CMAKE_FLAGS=%CMAKE_FLAGS% -DBOOST_INCLUDEDIR="%BOOST_ROOT%"
    REM set CMAKE_FLAGS=%CMAKE_FLAGS% -DBOOST_LIBRARYDIR="%BOOST_ROOT%\lib64-msvc-14.1"

build_script:
- cmd: |-
    REM APPVEYOR build_script:
    REM ----------------------
    mkdir build
    appveyor AddMessage "Building Showtime project with cmake"
    cmake -H. -B"%BUILD_FOLDER%\build" -G "%GENERATOR%" %CMAKE_FLAGS%
    cmake --build "%BUILD_FOLDER%\build" --config %CONFIGURATION%

before_test:
- cmd: |-
    REM APPVEYOR before_test:
    REM ---------------------
    REM Copy CZMQ dlls into build folder - manually until CMake can do this automagically
    appveyor AddMessage "Copy CZMQ dlls into build folder"
    if %CONFIGURATION% == Debug set LIBCZMQ_RUNTIME=libczmqd.dll
    if %CONFIGURATION% == Release set LIBCZMQ_RUNTIME=libczmq.dll
    cmake -E copy "%DEPENDENCY_DIR%\install\bin\%LIBCZMQ_RUNTIME%" "%BUILD_FOLDER%\build\bin\%CONFIGURATION%"

test_script:
- cmd: |-
    REM APPVEYOR test_script:
    REM ---------------------
    appveyor AddMessage "Running tests"
    appveyor AddTest "TestClient" -Framework ctest -Filename TestClient.exe -Outcome Running

    pushd "%BUILD_FOLDER%\build"
    set TESTCLIENT_LOG=%BUILD_FOLDER%\build\Testing\TestClient.log
    ctest -C %CONFIGURATION% --output-on-fail -V -O "%TESTCLIENT_LOG%" --timeout 60
    set TEST_OUTCOME=Passed
    if NOT %errorlevel% == 0 set TEST_OUTCOME=Failed
    call "%BUILD_FOLDER%\.appveyor\get_test_time.bat" %TESTCLIENT_LOG% TEST_DURATION
    
    SETLOCAL EnableDelayedExpansion
    for /f "Tokens=* Delims=" %%x in (%TESTCLIENT_LOG%) do set TESTCLIENT_LOG_CONTENTS=!TESTCLIENT_LOG_CONTENTS!%%x\n
    appveyor UpdateTest -Name "TestClient" -Framework ctest -Filename TestClient.exe -Outcome %TEST_OUTCOME% -Duration %TEST_DURATION% -StdOut "%TESTCLIENT_LOG_CONTENTS%"
    appveyor AddMessage "Tests complete - %TEST_OUTCOME%"
    ENDLOCAL
