version: '{build}'

branches:
  only:
  - master
  - develop
  - appveyor

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - include/

cache: 
- dependencies

clone_folder: c:/projects/showtime-cpp

image:
- Visual Studio 2017

configuration:
- Debug
- Release

platform:
- x64

environment:
  matrix:
  - GENERATOR: "Visual Studio 15 2017 Win64"

matrix:
  fast_finish: true

install:
- cmd: |-
    set BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER%
    set DEPENDENCY_DIR=%APPVEYOR_BUILD_FOLDER%\dependencies
    set BOOST_ROOT=C:\Libraries\boost_1_65_1

    REM APPVEYOR install:
    REM ----------------------
    call "%BUILD_FOLDER%\install_dependencies.bat"
    set CMAKE_FLAGS=-DCMAKE_PREFIX_PATH="%DEPENDENCY_DIR%\install;${CMAKE_PREFIX_PATH}"
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DUSE_LOCAL_BOOST=ON
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBOOST_ROOT="%BOOST_ROOT%"
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBOOST_INCLUDEDIR="%BOOST_ROOT%"
    set CMAKE_FLAGS=%CMAKE_FLAGS% -DBOOST_LIBRARYDIR="%BOOST_ROOT%\lib64-msvc-14.1"

build_script:
- cmd: |-
    REM APPVEYOR build_script:
    REM ----------------------
    mkdir build
    cmake -H. -B"%BUILD_FOLDER%\build" -G "%GENERATOR%" %CMAKE_FLAGS%
    cmake --build "%BUILD_FOLDER%\build" --config %CONFIGURATION%

before_test:
- cmd: |-
    REM APPVEYOR before_test:
    REM ---------------------
    REM Copy CZMQ dlls into build folder - manually until CMake can do this automagically
    if %CONFIGURATION% == Debug set LIBCZMQ_RUNTIME=libczmqd.dll
    if %CONFIGURATION% == Release set LIBCZMQ_RUNTIME=libczmq.dll
    cmake -E copy "%DEPENDENCY_DIR%\install\bin\%LIBCZMQ_RUNTIME%" "%BUILD_FOLDER%\build\bin\%CONFIGURATION%"

test_script:
- cmd: |-
    REM APPVEYOR test_script:
    REM ---------------------
    pushd "%BUILD_FOLDER%\build"
    ctest -C Debug -V --output-on-fail
    popd
