version: '{build}'
branches:
  only:
  - develop
cache: C:\projects\dependencies
clone_folder: c:\projects\showtime-cpp
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - GENERATOR: "Visual Studio 12 2013 Win64"
  - GENERATOR: "Visual Studio 14 2015 Win64"
  - GENERATOR: "Visual Studio 15 2017 Win64"

  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

before_build:
- cmd: |-
    cd C:\projects
    mkdir dependencies
    cd dependencies
    git clone https://github.com/mystfit/czmq.git
    cd czmq
    git checkout hunter-v4.1.0
    mkdir build
    mkdir install
    cmake -H. -B./build -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX="./install"
    cmake --build ./build --config %CONFIGURATION% --target INSTALL

    cd ..
    git clone https://github.com/mystfit/msgpack-c.git
    cd msgpack-c
    git checkout hunter-2.1.5
    mkdir build
    mkdir install
    cmake -H. -B./build -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX="./install"
    cmake --build ./build --config %CONFIGURATION% --target INSTALL

build_script:
- cmd: |-
    cmake -H. -B./build -G "%GENERATOR%"
    cmake --build ./build --config %CONFIGURATION%

    if %CONFIGURATION% == Debug set LIBCZMQ_DLL=libczmqd.dll
    if %CONFIGURATION% == Release set LIBCZMQ_DLL=libczmq.dll
    cmake -E copy C:\projects\dependencies\czmq\install\bin\%LIBCZMQ_DLL% C:\projects\showtime-cpp\build\bin\%CONFIGURATION%\

test_script:
- cmd: |-
    cd build
    ctest -C Debug -V --output-on-fail

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - include/
