trigger:
  branches:
    include:
      - master
      - develop
      - azure

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  toolset: 'msvc-14.2'
  toolset-platform: 'v142'
  build_dir: '$(Build.ArtifactStagingDirectory)\build'
  cmake_prefix: '$(build_dir)\dependencies\install\$(toolset)'
  solution: '$(build_dir)\Showtime.sln'

steps:
- checkout: self
  clean: true
  submodules: recursive

- task: PowerShell@2
  displayName: Install Visual Studio C++ Desktop workload
  inputs:
    targetType: 'inline'
    script: 'choco install visualstudio2019-workload-vctools --params "--includeOptional"'

- task: Cache@2
  displayName: Cache dependencies
  inputs:
    key: 'dependencies | "$(Agent.OS)"'
    restoreKeys: |
       dependencies | "$(Agent.OS)"
       dependencies
    path: $(cmake_prefix)
    cacheHitVar: DEPENDENCIES_RESTORED

- task: PowerShell@2
  displayName: Build dependencies
  condition: ne(variables.DEPENDENCIES_RESTORED, 'true')
  inputs:
    filePath: 'install_dependencies.ps1'
    arguments: '-config $(buildConfiguration) -build_dir $(build_dir) -toolset $(toolset)'
    errorActionPreference: 'continue'
    ignoreLASTEXITCODE: true
    pwsh: true
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CMake@1
  displayName: Generate CMake project
  inputs:
    workingDirectory: '$(build_dir)'
    cmakeArgs: >-
      -T $(toolset-platform)
      -S $(Build.SourcesDirectory) 
      -G "Visual Studio 16 2019" 
      -A $(buildPlatform) 
      -DCMAKE_PREFIX_PATH=$(cmake_prefix) 
      -DBUILD_SHARED=ON 
      -DBUILD_STATIC=ON 
      -DBUILD_DRAFTS=OFF 
      -DBUILD_TESTING=ON

- task: VSBuild@1
  displayName: Compile solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: Test solution
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: '**\*Test*.exe'
    searchFolder: '$(build_dir)'
