trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  toolset: 'msvc-14.2'
  build_dir: '$(Build.ArtifactStagingDirectory)/build'
  cmake_prefix: '$(build_dir)/dependencies/install/$(toolset)'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'install_dependencies.ps1'
    arguments: '-config $(buildConfiguration) -build_dir $(build_dir) -toolset $(toolset)'
    errorActionPreference: 'continue'
    ignoreLASTEXITCODE: true
    pwsh: true
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Cache@2
  inputs:
    key: 'dependencies | "$(Agent.OS)"'
    restoreKeys: |
       dependencies | "$(Agent.OS)"
       dependencies
    path: $(cmake_prefix)
  displayName: Cache dependencies

- task: CMake@1
  inputs:
    workingDirectory: '$(build_dir)'
    cmakeArgs: >-
      -T $(toolset)
      -S $(Build.SourcesDirectory) 
      -G "Visual Studio 16 2019" 
      -A $(buildPlatform) 
      -DCMAKE_PREFIX_PATH=$(cmake_prefix) 
      -DBUILD_SHARED=ON 
      -DBUILD_STATIC=ON 
      -DBUILD_DRAFTS=OFF 
      -DBUILD_TESTING=ON

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
