trigger:
  branches:
    include:
      - master
      - develop
      - azure

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  toolset: 'msvc-14.2'
  toolset-platform: 'v142'
  build_dir: '$(Build.ArtifactStagingDirectory)\build'
  cmake_prefix: '$(build_dir)\dependencies\install\$(toolset)'
  solution: '$(build_dir)\Showtime.sln'

steps:
- checkout: self
  clean: true
  submodules: recursive

- task: PowerShell@2
  displayName: Install Visual Studio C++ Desktop workload
  inputs:
    targetType: 'inline'
    script: |
      choco install visualstudio2019-workload-nativedesktop --params "--includeRecommended"
      # $VS_path = $(vswhere -format value -property installationPath)
      # Write-Host "##vso[task.setvariable variable=VS_path;]$(vswhere -format value -property installationPath)"
      # ls $VS_path\Common7\IDE\Extensions\em3ozjcu.15r

- task: Cache@2
  displayName: Cache dependencies
  inputs:
    key: 'dependencies2 | "$(Agent.OS)"'
    restoreKeys: |
       dependencies2 | "$(Agent.OS)"
       dependencies2
    path: $(cmake_prefix)
    cacheHitVar: DEPENDENCIES_RESTORED

- task: PowerShell@2
  displayName: Build dependencies
  condition: ne(variables.DEPENDENCIES_RESTORED, 'true')
  inputs:
    filePath: 'install_dependencies.ps1'
    arguments: '-config debug,release -build_dir $(build_dir) -toolset $(toolset)'
    errorActionPreference: 'continue'
    ignoreLASTEXITCODE: true
    pwsh: true
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CMake@1
  displayName: Generate CMake project
  inputs:
    workingDirectory: '$(build_dir)'
    cmakeArgs: >-
      -T $(toolset-platform)
      -S $(Build.SourcesDirectory) 
      -G "Visual Studio 16 2019" 
      -A $(buildPlatform) 
      -DCMAKE_PREFIX_PATH=$(cmake_prefix) 
      -DBUILD_SHARED=ON 
      -DBUILD_STATIC=ON 
      -DBUILD_DRAFTS=OFF 
      -DBUILD_TESTING=ON

- task: VSBuild@1
  displayName: Compile solution (debug)
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: 'Debug'
    maximumCpuCount: true
    
- task: VSBuild@1
  displayName: Compile solution (release)
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: 'Release'
    maximumCpuCount: true

- task: VSTest@2
  displayName: Test solution
  inputs:
    platform: '$(buildPlatform)'
    configuration: 'Debug'
    testAssemblyVer2: '**\*Test*.exe'
    searchFolder: '$(build_dir)'
    runInParallel: True
    # pathtoCustomTestAdapters: '$(VS_path)\Common7\IDE\Extensions\em3ozjcu.15r'
