# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "sylabs/singularity-3.2-ubuntu-bionic64"
  config.vm.box_version = "20190515.0.0"
  config.vm.synced_folder "../", "/vagrant-showtime-src"
  config.vm.synced_folder "../build", "/vagrant-showtime-build"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2  
    vb.memory = "4096"
  end
  
  config.vm.provision "shell", env: {"SINGULARITYENV_SHOWTIME_SOURCE" => "/vagrant-showtime-src"}, inline: <<-SHELL
    sudo mkdir -p /VMs
    yes | sudo singularity build /VMs/build-android.sif /vagrant/build-android.def
  SHELL
end
