version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:latest
        environment:
          BUILD_FOLDER: $CIRCLE_WORKING_DIRECTORY
          GENERATOR: "Unix Makefiles"
          USE_LOCAL_BOOST: 1
      - dependencies:
        - override:
          - run: echo y | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          - run: brew update
          - run: brew install msgpack
          - run: brew install fmt
          - run: brew install czmq
          - run: brew install boost

    steps:
      - checkout
      - echo "Working in $BUILD_FOLDER"
      
