# ################################################################################
# #  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
# #  Read the zproject/README.md for information about making permanent changes. #
# ################################################################################

# if (NOT MSVC)
#     include(FindPkgConfig)
#     pkg_check_modules(PC_CZMQ "libczmq")
#     if (NOT PC_CZMQ_FOUND)
#         pkg_check_modules(PC_CZMQ "libczmq")
#     endif (NOT PC_CZMQ_FOUND)
#     if (PC_CZMQ_FOUND)
#         # add CFLAGS from pkg-config file, e.g. draft api.
#         add_definitions(${PC_CZMQ_CFLAGS} ${PC_CZMQ_CFLAGS_OTHER})
#         # some libraries install the headers is a subdirectory of the include dir
#         # returned by pkg-config, so use a wildcard match to improve chances of finding
#         # headers and SOs.
#         set(PC_CZMQ_INCLUDE_HINTS ${PC_CZMQ_INCLUDE_DIRS} ${PC_CZMQ_INCLUDE_DIRS}/*)
#         set(PC_CZMQ_LIBRARY_HINTS ${PC_CZMQ_LIBRARY_DIRS} ${PC_CZMQ_LIBRARY_DIRS}/*)
#     endif(PC_CZMQ_FOUND)
# endif (NOT MSVC)

# find_path (
#     CZMQ_INCLUDE_DIRS
#     NAMES czmq.h
#     HINTS ${PC_CZMQ_INCLUDE_HINTS}
# )

# find_library (
#     CZMQ_LIBRARIES
#     NAMES czmq
#     HINTS ${PC_CZMQ_LIBRARY_HINTS}
# )

# include(FindPackageHandleStandardArgs)

# find_package_handle_standard_args(
#     CZMQ
#     REQUIRED_VARS CZMQ_LIBRARIES CZMQ_INCLUDE_DIRS
# )
# mark_as_advanced(
#     CZMQ_FOUND
#     CZMQ_LIBRARIES CZMQ_INCLUDE_DIRS
# )

# ################################################################################
# #  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
# #  Read the zproject/README.md for information about making permanent changes. #
# ################################################################################


set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH ON)
find_package(PkgConfig)
pkg_check_modules(PC_CZMQ QUIET czmq)

set(CZMQ_VERSION ${PC_CZMQ_VERSION})
find_library(CZMQ_LIBRARY NAMES libczmq.so libczmq.dylib libczmq.dll
             PATHS ${PC_CZMQ_LIBDIR} ${PC_CZMQ_LIBRARY_DIRS})
find_library(CZMQ_STATIC_LIBRARY NAMES libczmq-static.a libczmq.a libczmq.dll.a
             PATHS ${PC_CZMQ_LIBDIR} ${PC_CZMQ_LIBRARY_DIRS})

if(CZMQ_LIBRARY AND CZMQ_STATIC_LIBRARY)
    set(CZMQ_FOUND ON)
endif()

if (TARGET czmq)
    # avoid errors defining targets twice
    return()
endif()

add_library(czmq SHARED IMPORTED)
set_property(TARGET czmq PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${PC_CZMQ_INCLUDE_DIRS})
set_property(TARGET czmq PROPERTY IMPORTED_LOCATION ${CZMQ_LIBRARY})

add_library(czmq-static STATIC IMPORTED ${PC_CZMQ_INCLUDE_DIRS})
set_property(TARGET czmq-static PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${PC_CZMQ_INCLUDE_DIRS})
set_property(TARGET czmq-static PROPERTY IMPORTED_LOCATION ${CZMQ_STATIC_LIBRARY})
