//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PlugEvent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PlugEvent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PlugEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PlugEvent() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          showtime_dotnetPINVOKE.delete_PlugEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PlugEvent() : this(showtime_dotnetPINVOKE.new_PlugEvent__SWIG_0(), true) {
  }

  public PlugEvent(PlugEvent.Events e, ZstPlug p) : this(showtime_dotnetPINVOKE.new_PlugEvent__SWIG_1((int)e, ZstPlug.getCPtr(p)), true) {
  }

  public PlugEvent.Events event_() {
    PlugEvent.Events ret = (PlugEvent.Events)showtime_dotnetPINVOKE.PlugEvent_event_(swigCPtr);
    return ret;
  }

  public ZstPlug plug() {
    global::System.IntPtr cPtr = showtime_dotnetPINVOKE.PlugEvent_plug(swigCPtr);
    ZstPlug ret = (cPtr == global::System.IntPtr.Zero) ? null : new ZstPlug(cPtr, false);
    return ret;
  }

  public enum Events {
    DEFAULT = 0,
    CREATED,
    DESTROYED,
    HIT
  }

}
