//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PlugCallback : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PlugCallback(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PlugCallback obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PlugCallback() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          showtime_dotnetPINVOKE.delete_PlugCallback(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PlugCallback() : this(showtime_dotnetPINVOKE.new_PlugCallback(), true) {
    SwigDirectorConnect();
  }

  public virtual void run(ZstPlug plug) {
    if (SwigDerivedClassHasMethod("run", swigMethodTypes0)) showtime_dotnetPINVOKE.PlugCallback_runSwigExplicitPlugCallback(swigCPtr, ZstPlug.getCPtr(plug)); else showtime_dotnetPINVOKE.PlugCallback_run(swigCPtr, ZstPlug.getCPtr(plug));
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("run", swigMethodTypes0))
      swigDelegate0 = new SwigDelegatePlugCallback_0(SwigDirectorrun);
    showtime_dotnetPINVOKE.PlugCallback_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(PlugCallback));
    return hasDerivedMethod;
  }

  private void SwigDirectorrun(global::System.IntPtr plug) {
    run((plug == global::System.IntPtr.Zero) ? null : new ZstPlug(plug, false));
  }

  public delegate void SwigDelegatePlugCallback_0(global::System.IntPtr plug);

  private SwigDelegatePlugCallback_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(ZstPlug) };
}
