//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum PlugTypes {
  INT_PLUG = 0,
  INT_ARR_PLUG,
  FLOAT_PLUG,
  FLOAT_ARR_PLUG,
  STRING_PLUG
}
