//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class showtime_dotnet {
  public static ZstIntPlug convert_to_int_plug(ZstPlug plug) {
    global::System.IntPtr cPtr = showtime_dotnetPINVOKE.convert_to_int_plug(ZstPlug.getCPtr(plug));
    ZstIntPlug ret = (cPtr == global::System.IntPtr.Zero) ? null : new ZstIntPlug(cPtr, false);
    return ret;
  }

}
