//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ZstIntPlug : ZstPlug {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ZstIntPlug(global::System.IntPtr cPtr, bool cMemoryOwn) : base(showtime_dotnetPINVOKE.ZstIntPlug_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ZstIntPlug obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ZstIntPlug() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          showtime_dotnetPINVOKE.delete_ZstIntPlug(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ZstIntPlug(ZstURI uri) : this(showtime_dotnetPINVOKE.new_ZstIntPlug(ZstURI.getCPtr(uri)), true) {
  }

  public void fire(int value) {
    showtime_dotnetPINVOKE.ZstIntPlug_fire(swigCPtr, value);
  }

  public override void recv(SWIGTYPE_p_msgpack__object arg0) {
    showtime_dotnetPINVOKE.ZstIntPlug_recv(swigCPtr, SWIGTYPE_p_msgpack__object.getCPtr(arg0));
    if (showtime_dotnetPINVOKE.SWIGPendingException.Pending) throw showtime_dotnetPINVOKE.SWIGPendingException.Retrieve();
  }

  public int get_value() {
    int ret = showtime_dotnetPINVOKE.ZstIntPlug_get_value(swigCPtr);
    return ret;
  }

}
